target:
	gcc -Wall -g -o l10e01 -pthread l10e01.c -lm
	gcc -Wall -g -o l10e02util -pthread l10e02util.c -lm
	gcc -Wall -g -o l10e02 -pthread l10e02.c -lm

clean:
	rm -rf *~
	rm -rf l10e01
	rm -rf l10e02util
	rm -rf l10e02
