#
# Makefile
#

target :
	echo "Use e01a, e01b, e01c, e01d"

e01a :
	gcc -Wall l03e01a.c -o a.o
	./a.o
e01b :
	gcc -Wall l03e01b.c -o b.o
	./b.o

e01c :
	gcc -Wall l03e01c.c -o c.o
	./c.o

e01d :
	gcc -Wall l03e01d.c -o d.o
	./d.o

clean :
	rm -f *.o


